Algoritmo "Lógico"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/06/2020
Var
// Seção de Declarações das variáveis 
a,b,c : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
a<-3
b<-5
c<-1

escreva(a>b)
escreva((a=b) ou (b<c))
escreva((a=b) ou (b>c))
Fimalgoritmo